
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.renderer/template-version: 1.0.0
    k8s.renderer/commit: {{ .Vars.CommitSHA }}
    k8s.renderer/branch: {{ .Vars.Branch }}
    k8s.renderer/vcs-url: {{ .Vars.VCSURL }}
    k8s.renderer/render-time: {{ .RenderTime }}
  labels:
    app.kubernetes.io/name: {{ .App.Name }}
    app.kubernetes.io/part-of: {{ .App.PartOf }}
    app.kubernetes.io/version: {{ .Vars.BuildVersion }}
    app.kubernetes.io/managed-by: k8s.renderer
  name: {{ .App.Name }}
  namespace: {{ .Namespace }}
spec:
  replicas: {{ .App.Replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .App.Name }}
      app.kubernetes.io/part-of: {{ .App.PartOf }}
      app.kubernetes.io/version: {{ .Vars.BuildVersion }}
  template:
    metadata:
      annotations:
        k8s.renderer/template-version: 1.0.0
        k8s.renderer/commit: {{ .Vars.CommitSHA }}
        k8s.renderer/branch: {{ .Vars.Branch }}
        k8s.renderer/vcs-url: {{ .Vars.VCSURL }}
        k8s.renderer/render-time: {{ .RenderTime }}
      labels:
        app.kubernetes.io/name: {{ .App.Name }}
        app.kubernetes.io/part-of: {{ .App.PartOf }}
        app.kubernetes.io/version: {{ .Vars.BuildVersion }}
        app.kubernetes.io/managed-by: k8s.renderer
      namespace: {{ .Namespace }}
    spec:
      containers:
        - envFrom: {{ range $secret := .Env.Secrets }}
            - secretRef:
                name: {{ $secret }} {{ end }}
          image: {{ .Vars.DockerRegistry }}/{{ .App.Name }}:{{ .Vars.BuildVersion }}
          imagePullPolicy: Always
          name: {{ .App.Name }}
          ports:
            - containerPort: {{ .App.Port }}
              name: http
              protocol: TCP
          volumeMounts: {{ range $mount := .Mounts }}
            - mountPath: {{ $mount.Path }}
              name: {{ $mount.Name }}
              readOnly: {{ $mount.ReadOnly }} {{ end }}
      imagePullSecrets:
        - name: {{ .Vars.ImagePullSecret }}
      volumes: {{ range $secret := .SecretVolumes }}
        - name: {{ $secret.Name }}
          secret:
            defaultMode: {{ $secret.Mode }}
            optional: false
            secretName: {{ $secret.SecretName }}  {{ end }}
