apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.renderer/template-version: 1.0.0
    k8s.renderer/commit: {{ .Vars.CommitSHA }}
    k8s.renderer/branch: {{ .Vars.Branch }}
    k8s.renderer/vcs-url: {{ .Vars.VCSURL }}
    k8s.renderer/render-time: {{ .RenderTime }}
    prometheus.io/scrape: "true"
    prometheus.io/path: "{{ .App.Metrics.Path }}"
    prometheus.io/port: "{{ .App.Port }}"
  labels:
    app.kubernetes.io/name: {{ .App.Name }}
    app.kubernetes.io/part-of: {{ .App.PartOf }}
    app.kubernetes.io/version: {{ .Vars.BuildVersion }}
    app.kubernetes.io/managed-by: k8s.renderer
  name: {{ .App.Name }}
  namespace: {{ .Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .App.Port }}
  selector:
    app.kubernetes.io/name: {{ .App.Name }}
    app.kubernetes.io/part-of: {{ .App.PartOf }}
    app.kubernetes.io/version:  {{ .Vars.BuildVersion }}