name: go-release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true
          cache-dependency-path: go.sum
          
      - name: Build
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o k8s-render ./cmd/k8s-render
      
      - name: List output files
        run: ls -lh ./k8s-render
      
      - name: Prepare release package
        run: |
          mkdir -p release-package
          cp ./k8s-render release-package/
          cp ./templates release-package/

          tar -czf release-package.tar.gz -C release-package .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: release-package.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
